# Generated by Django 5.1 on 2024-09-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmapping',
            name='long_url',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='urlmapping',
            name='short_url',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
